spring.application.name=passgeneration
spring.datasource.url=jdbc:mysql://localhost:3306/passgeneration?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1910

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=meusegredosegurocommaisde32caracteres123