spring.application.name=passgeneration
spring.datasource.url=jdbc:mysql://db:3306/passgeneration?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1910
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=chaveUltraSecretaParaAutenticacaoJWT2026SistemaSeguro